### ISSUE TITLE
Fatal error when template parsing fails

### ISSUE THREAD

**Issue by piercemoore** [cif/handlebar-rider#12]
```
23:27:16 Handlebars.1  | [ Log ] File change detected: 'js/templates/msg/creation/user_placeholder.hb'
23:27:16 Handlebars.1  | 
23:27:16 Handlebars.1  | /usr/lib/node_modules/handlebar-rider/node_modules/handlebars/lib/handlebars/compiler/parser.js:112
23:27:16 Handlebars.1  |     throw new Error(str);
23:27:16 Handlebars.1  |           ^
23:27:16 Handlebars.1  | Error: Parse error on line 2:
23:27:16 Handlebars.1  | ...ground-image: url({{hero) no-repeat top 
23:27:16 Handlebars.1  | -----------------------^
23:27:16 Handlebars.1  | Expecting 'DATA', 'ID', got 'INVALID'
23:27:16 Handlebars.1  |     at Object.parseError (/usr/lib/node_modules/handlebar-rider/node_modules/handlebars/lib/handlebars/compiler/parser.js:112:11)
23:27:16 Handlebars.1  |     at Object.parse (/usr/lib/node_modules/handlebar-rider/node_modules/handlebars/lib/handlebars/compiler/parser.js:164:22)
23:27:16 Handlebars.1  |     at Object.exports.attach.Handlebars.parse (/usr/lib/node_modules/handlebar-rider/node_modules/handlebars/lib/handlebars/compiler/base.js:15:28)
23:27:16 Handlebars.1  |     at Object.exports.attach.Handlebars.precompile (/usr/lib/node_modules/handlebar-rider/node_modules/handlebars/lib/handlebars/compiler/compiler.js:1247:24)
23:27:16 Handlebars.1  |     at precompile (/usr/lib/node_modules/handlebar-rider/lib/handlebar-rider.js:86:25)
23:27:16 Handlebars.1  |     at /usr/lib/node_modules/handlebar-rider/lib/handlebar-rider.js:110:82
23:27:16 Handlebars.1  |     at fs.readFile (fs.js:176:14)
23:27:16 Handlebars.1  |     at Object.oncomplete (fs.js:297:15)
23:27:16 Handlebars.1  | exited with code 0
23:27:16 system        | sending SIGTERM to all processes
```

**Comment by piercemoore** [comment]
I'll see if this is still an issue, but I'm almost positive that it was just because I was writing 

``` js
throw new Error(str)
```

Instead of the correct

``` js
throw str
```

I will test though.

**Comment by piercemoore** [comment]
Oooh wait no that is a properly formed error. This is coming from the Handlebars precompiler itself. I'll write in a way for this not to be fatal to `watch()`.

**Comment by piercemoore** [comment]
I've written in a try/catch block that should take care of it. Testing now.

**Comment by piercemoore** [comment]
Bug is confirmed as fixed.

```
12:22:39 Presentation_Handlebars.1 | [ Log ] File change detected: 'js/templates/post/comment.hb'
12:22:39 Presentation_Handlebars.1 | [ Log ] Checking to see if we already compiled this....
12:22:39 Presentation_Handlebars.1 | [ Error ] [Error: Parse error on line 1:
12:22:39 Presentation_Handlebars.1 | ...module-body-copy">{{text</span><br><span
12:22:39 Presentation_Handlebars.1 | -----------------------^
12:22:39 Presentation_Handlebars.1 | Expecting 'DATA', 'ID', got 'INVALID']
```

**Comment by piercemoore** [comment]
Commit 028b29920b4bbd8a237ad1396158c02227ca2741 fixes this issue.
