### ISSUE TITLE
Failure when template directory is empty, even if the path is valid

### ISSUE THREAD

**Issue by piercemoore** [cif/handlebar-rider#13]
```
22:50:34 Admin_Handlebars.1        | [ Warning ] All files of the following types will be compiled: .hb, .hbs, .handlebars
22:50:34 Admin_Handlebars.1        | 
22:50:34 Admin_Handlebars.1        | /usr/lib/node_modules/handlebar-rider/lib/handlebar-rider.js:159
22:50:34 Admin_Handlebars.1        |             throw error('There are no files for Handlebar-Rider to compile. Di
22:50:34 Admin_Handlebars.1        |                   ^
22:50:34 DataService.1             | Setting app mode to dev
22:50:34 Admin_Handlebars.1        | ReferenceError: error is not defined
22:50:34 Admin_Handlebars.1        |     at readAndCompile (/usr/lib/node_modules/handlebar-rider/lib/handlebar-rider.js:159:19)
22:50:34 Admin_Handlebars.1        |     at readTemplatesDirectory (/usr/lib/node_modules/handlebar-rider/lib/handlebar-rider.js:35:30)
22:50:34 Admin_Handlebars.1        |     at Object.oncomplete (fs.js:297:15)
```

**Comment by piercemoore** [comment]
It turns out, of course that this is not a fatal error on the part of Handlebar-rider. This is a fatal dev error (me). 

``` js
throw error('Error Message');
```

Is just wrong. It is now 

``` js
throw "Error Message";
```

**Comment by piercemoore** [comment]
Commit 028b29920b4bbd8a237ad1396158c02227ca2741 fixes this issue.
